### PR TITLE
Rework project

### PR DESCRIPTION
**Pull request by benkiefer**
I spoke with @williamsbdev this morning, and was able to fix where foundation was shoving the modal by configuring the root_element for reveal.

This makes it possible to use the click and find helpers again, which from what we discussed yesterday is a lot of the reason this project exists. 

The advantage to using foundation directly for managing modals is that we can now handle multiple modals on a page, where the current project prefers that there is one modal per route.

Thoughts? Concerns?

@williamsbdev and I got this tested, but were seeing a weird issue when testing in phantomjs with define. Any help/thoughts on this you can pass along would be a big help.

### CODE REVIEW

**Comment by williamsbdev** [comment]
I will take a look at the issue tonight to see if a simple upgrade of
ember-cli will help. I think that may be part of the issue.

On Friday, March 20, 2015, Ben Kiefer notifications@github.com wrote:

> I spoke with @williamsbdev https://github.com/williamsbdev this
> morning, and was able to fix where foundation was shoving the modal by
> configuring the root_element for reveal.
> 
> This makes it possible to use the click and find helpers again, which from
> what we discussed yesterday is a lot of the reason this project exists.
> 
> The advantage to using foundation directly for managing modals is that we
> can now handle multiple modals on a page, where the current project prefers
> that there is one modal per route.
> 
> Thoughts? Concerns?
> 
> @williamsbdev https://github.com/williamsbdev and I got this tested,
> but were seeing a weird issue when testing in phantomjs with define. Any
> 
> ## help/thoughts on this you can pass along would be a big help.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/toranb/ember-cli-foundation-modal/pull/2
> Commit Summary
> - add intellij files to gitignore
> - change foundation modal over to use initializer that sets
>   root_element of foundation's reveal to a variable customizable by the ember
>   app
> - updating the readme
> 
> File Changes
> - _M_ .gitignore
>   https://github.com/toranb/ember-cli-foundation-modal/pull/2/files#diff-0
>   (1)
> - _M_ .jshintrc
>   https://github.com/toranb/ember-cli-foundation-modal/pull/2/files#diff-1
>   (1)
> - _M_ README.md
>   https://github.com/toranb/ember-cli-foundation-modal/pull/2/files#diff-2
>   (37)
> - _D_ addon/.gitkeep
>   https://github.com/toranb/ember-cli-foundation-modal/pull/2/files#diff-3
>   (0)
> - _A_ addon/initializers/foundation-initializer.js
>   https://github.com/toranb/ember-cli-foundation-modal/pull/2/files#diff-4
>   (12)
> - _D_ addon/mixins/foundation-app-modal.js
>   https://github.com/toranb/ember-cli-foundation-modal/pull/2/files#diff-5
>   (14)
> - _D_ addon/mixins/foundation-modal.js
>   https://github.com/toranb/ember-cli-foundation-modal/pull/2/files#diff-6
>   (17)
> - _D_ app/.gitkeep
>   https://github.com/toranb/ember-cli-foundation-modal/pull/2/files#diff-7
>   (0)
> - _A_ app/initializers/foundation-initializer.js
>   https://github.com/toranb/ember-cli-foundation-modal/pull/2/files#diff-8
>   (6)
> - _R_ tests/acceptance/.gitkeep
>   https://github.com/toranb/ember-cli-foundation-modal/pull/2/files#diff-9
>   (0)
> - _D_ tests/acceptance/acceptance-test.js
>   https://github.com/toranb/ember-cli-foundation-modal/pull/2/files#diff-10
>   (38)
> - _D_ tests/dummy/app/controllers/application.js
>   https://github.com/toranb/ember-cli-foundation-modal/pull/2/files#diff-11
>   (6)
> - _D_ tests/dummy/app/controllers/foo.js
>   https://github.com/toranb/ember-cli-foundation-modal/pull/2/files#diff-12
>   (6)
> - _M_ tests/dummy/app/router.js
>   https://github.com/toranb/ember-cli-foundation-modal/pull/2/files#diff-13
>   (1)
> - _M_ tests/dummy/app/templates/application.hbs
>   https://github.com/toranb/ember-cli-foundation-modal/pull/2/files#diff-14
>   (2)
> - _D_ tests/dummy/app/templates/foo.hbs
>   https://github.com/toranb/ember-cli-foundation-modal/pull/2/files#diff-15
>   (10)
> - _A_ tests/unit/initializers/foundation-initializer-test.js
>   https://github.com/toranb/ember-cli-foundation-modal/pull/2/files#diff-16
>   (26)
> 
> Patch Links:
> - https://github.com/toranb/ember-cli-foundation-modal/pull/2.patch
> - https://github.com/toranb/ember-cli-foundation-modal/pull/2.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/toranb/ember-cli-foundation-modal/pull/2.

## 

Sent from Gmail Mobile

**Comment by toranb** [comment]
Wow this is some excellent rework @benkiefer !!! Also thanks for taking a look tonight @williamsbdev ! If you still want me to do this upgrade I should be free Sunday afternoon/night this weekend!

**Comment by benkiefer** [comment]
@williamsbdev found the issue that was causing phantomjs to blow up, it has been merged into this PR, so we're ready to go

**Comment by toranb** [comment]
@benkiefer as I was looking over the changes I decided to add a simple acceptance test to prove this would work w/ ember-testing (the only real reason this addon was created). The issue is that the tests don't seem to work after this refactor (or I don't know what needs to be configured in the dummy app to use your changes correctly). Either way I'd like to have a simple acceptance test that proves this new refactor is still ember-testing friendly.

I've started the work at the repository below. At the current time if you pull this down and run "ember server" you can see that it works as expected using the dummy app. Yet when I run the tests it doesn't seem to wait for the reveal-modal to do it's thing.

If you can help me get this 1 test passing I'd be happy to pull in this change!

https://bitbucket.org/toranb/broken-foundation-modal-addon/commits/all

**Comment by benkiefer** [comment]
We can definitely get a test put together. Here's a [link](https://github.com/emberjs/ember.js/issues/5494) to the open issue in ember that is causing you pain.

Towards the end, you'll find the only solution that I've been able to get working consistently. Basically, Thread.sleep(). At least the community is aware of the issue...

**Comment by toranb** [comment]
I was able to use that custom waitFor function and in Chrome all is good :)

https://bitbucket.org/toranb/broken-foundation-modal-addon/commits/f340c22f60c6b1391b765ab10fbf1b6e5892aca8

The issue I'm trying to understand now is why phantomJS hangs (as travis-ci would run this/ local test builds would hang). Any idea what you did special to ensure phantomJS wouldn't hang when you ran your tests using this technique?

**Comment by benkiefer** [comment]
I commented out everything after clicking the open button, and saw this error:

```
 TypeError: 'undefined' is not a function (near '...}.bind(this), settings.ani...')
```

Looks like the problem is caused by [this issue](https://github.com/ariya/phantomjs/issues/10522) with phantomjs.

I've pulled in the changes that they recommend (the bind polyfill), and all is well.

**Comment by benkiefer** [comment]
I also merged in your tests and the format of your waitFor.

**Comment by williamsbdev** [comment]
We should be able to just add the es5 shim tithe project and then add the
source file to the tests/index.html.

On Sunday, March 22, 2015, Ben Kiefer notifications@github.com wrote:

> I commented out everything after clicking the open button, and saw this
> error:
> 
>  TypeError: 'undefined' is not a function (near '...}.bind(this), settings.ani...')
> 
> Looks like the problem is caused by this issue
> https://github.com/ariya/phantomjs/issues/10522 with phantomjs.
> 
> I've pulled in the changes that they recommend (the bind polyfill), and
> all is well.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/toranb/ember-cli-foundation-modal/pull/2#issuecomment-84629954
> .

## 

Sent from Gmail Mobile

**Comment by toranb** [comment]
@williamsbdev I can do the ES5 shim rework after we pull this in as it's just for testing anyway. Thanks for identifying the busted phantomJS issue @benkiefer 

The code looks solid now and has some examples to show how it's tested. The only part I don't see anything about in the README is changing the rootElement (if you are not using the default).

Does any configuration option like this exist?

**Comment by benkiefer** [comment]
Both changes are complete. The README has been updated and I switched over to the es5 shims.

**Comment by toranb** [comment]
This looks great @benkiefer

**Comment by toranb** [comment]
Just published 0.2.0 to npm as this was a huge shift from the original 0.1.x series of this addon. Thanks again for all the hard work reverse engineering both the production issues (rootElement) and the appropriate method to test this with!

https://www.npmjs.com/package/ember-cli-foundation-modal

**Pull request merged**
