### PR TITLE
Updating README and package.json

### PR DESCRIPTION
**Pull request by williamsbdev**

### CODE REVIEW

**Comment by toranb** [comment]
I just added you as a contributor /npm author :) thanks for the quick work dude!

**Comment by toranb** [comment]
Can you do the npm publish of this when you are good to go?

**Comment by williamsbdev** [comment]
Yes. I will do that. I broke the NPM Downloads image and am fixing that
right now.

**Comment by williamsbdev** [comment]
Done. I'm out for tonight. Later dude!!!

**Pull request merged**
